/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import form.db_connection;
import form.Manager;
import form.FrontDesk;
import form.ServiceRecords;
import javax.swing.JOptionPane;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.*;
import javax.swing.JFrame;

/**
 *
 * @author saurabhshanbhag
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form WolfInnApp
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Login_button = new javax.swing.JButton();
        id = new javax.swing.JLabel();
        staffid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Silom", 2, 24)); // NOI18N
        jLabel1.setText("Wolf Inns");

        Login_button.setText("Submit");
        Login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Submit(evt);
            }
        });

        id.setText("Staff ID");

        staffid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(id)
                .addGap(24, 24, 24)
                .addComponent(staffid, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(231, 231, 231))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Login_button)
                        .addGap(246, 246, 246))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id)
                    .addComponent(staffid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Login_button)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Submit(java.awt.event.ActionEvent evt) {                        
        // TODO add your handling code here:
        //JFrame jf = new JFrame();

        db_connection db = new db_connection();
        Connection conn;
        Statement stmt;
        ResultSet rs;
        try {

            String sid = staffid.getText();
            int id = Integer.parseInt(sid);
            conn = db.connect_db();
            stmt = conn.createStatement();
            boolean s,f,mr;
            s = f = mr = false;
            rs = stmt.executeQuery("select * from cateringstaff where staffid = " + id);
            if (rs.first()) {    
                ServiceRecords sr = new ServiceRecords();
                sr.setVisible(true);
                s = true;
            }
            rs = null;
            rs = stmt.executeQuery("select * from roomservicestaff where staffid = " + id);
            if (s == false && rs.first()) {    
                ServiceRecords sr = new ServiceRecords();
                sr.setVisible(true);
                s = true;
            }
            rs = null;
            rs = stmt.executeQuery("select * from frontdeskstaff where staffid = " + id);
            if (s == false && rs.first()) {    
                FrontDesk fd = new FrontDesk();
                fd.setVisible(true);
                f = true;
            }
            rs = null;
            rs = stmt.executeQuery("select * from manager where staffid = " + id);
            if (s == false && f == false && rs.first()) {    
                Manager m = new Manager();
                m.setVisible(true);
                mr = true;
            }
            if(s == false && f == false && mr == false){
                JFrame jf = new JFrame();
                JOptionPane.showMessageDialog(jf,"INVALID LOGIN DETAILS","LOGIN ERROR",JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            //e.printStackTrace();
            System.out.println("Cannot connect to database");
        }

//            connect_db();
//        } catch(Exception e){
//            e.printStackTrace();
//            System.out.println("Failed");
//        }
//        
//        String pwd = password.getText();
//        String sid = StaffID_text.getText();
//        
//        if(sid.equals("100") && pwd.equals("mary123")){
//            sysExit();
//            //if sid belongs to manager)
//                //mng.setVisible(true);
//            //if sid belongs to front desk
//               fd.setVisible(true);
//            //if sid belongs to others
//                //sr.setVisible(true);
//        }
//        
//        else if(sid.equals("106") && pwd.equals("olivia123")){
//            sysExit();
//            fd.setVisible(true);
//        } 
//        else{
//            JOptionPane.showMessageDialog(null,"INVALID LOGIN DETAILS","LOGIN ERROR",JOptionPane.ERROR_MESSAGE);
//            password.setText(null);
//            StaffID_text.setText(null);
//            
//        }
    }                                            

    private void staffidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffidActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_staffidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
    
    public void sysExit(){
        WindowEvent winClosing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Login_button;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField staffid;
    // End of variables declaration//GEN-END:variables
}
