/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author neelkapadia
 */
public class OtherStaff extends javax.swing.JFrame {

    /**
     * Creates new form OtherStaff
     */
    public OtherStaff() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenerateInvoice = new javax.swing.JRadioButton();
        UpdateInvoice = new javax.swing.JRadioButton();
        GetAmount = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        AddRecord = new javax.swing.JRadioButton();
        UpdateRecord = new javax.swing.JRadioButton();
        DeleteRecord = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        ViewRecord = new javax.swing.JRadioButton();
        Submit = new javax.swing.JButton();

        GenerateInvoice.setText("Generate Invoice");

        UpdateInvoice.setText("Update Invoice");

        GetAmount.setText("Get total amount owed");

        jLabel1.setText("Select the task you want to perform:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Silom", 2, 24)); // NOI18N
        jLabel2.setText("Wolf Inns");

        buttonGroup1.add(AddRecord);
        AddRecord.setText("Add service record");

        buttonGroup1.add(UpdateRecord);
        UpdateRecord.setText("Update service record");

        buttonGroup1.add(DeleteRecord);
        DeleteRecord.setText("Delete service record");

        jLabel3.setText("Select the task you want to perform:");

        buttonGroup1.add(ViewRecord);
        ViewRecord.setText("View service records");

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(AddRecord)
                            .addComponent(UpdateRecord)
                            .addComponent(DeleteRecord)
                            .addComponent(ViewRecord)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(Submit)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AddRecord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UpdateRecord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DeleteRecord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewRecord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Submit)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        String addRecord = AddRecord.getText();
        String updateRecord = UpdateRecord.getText();
        String deleteRecord = DeleteRecord.getText();
        String viewRecord = ViewRecord.getText();
        System.out.print(addRecord + " " + updateRecord + " " + deleteRecord + " " + viewRecord);
        
        if(AddRecord.isSelected()){
            //open add record form
            
        } else if(UpdateRecord.isSelected()){
            //open update record form
            
        } else if(DeleteRecord.isSelected()){
            //open delete record form
        } else if(ViewRecord.isSelected()){
            //view list of records
        } else {
            //throw error
        }
        //JOptionPane.showMessageDialog(frame, "Hello World");
        
    }//GEN-LAST:event_SubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OtherStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OtherStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OtherStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OtherStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OtherStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AddRecord;
    private javax.swing.JRadioButton DeleteRecord;
    private javax.swing.JRadioButton GenerateInvoice;
    private javax.swing.JRadioButton GetAmount;
    private javax.swing.JButton Submit;
    private javax.swing.JRadioButton UpdateInvoice;
    private javax.swing.JRadioButton UpdateRecord;
    private javax.swing.JRadioButton ViewRecord;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
