/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author saurabhshanbhag
 */
public class ServiceRecords extends javax.swing.JFrame {

    /**
     * Creates new form ServiceRecords
     */
    public ServiceRecords() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        addServiceRecord = new javax.swing.JRadioButton();
        updateServiceRecord = new javax.swing.JRadioButton();
        deleteServiceRecord = new javax.swing.JRadioButton();
        viewServiceRecord = new javax.swing.JRadioButton();
        submitServiceRecord = new javax.swing.JButton();
        Home2 = new javax.swing.JButton();
        Logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonGroup1.add(addServiceRecord);
        addServiceRecord.setText("Add Service Record");

        buttonGroup1.add(updateServiceRecord);
        updateServiceRecord.setText("Update Service Record");
        updateServiceRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateServiceRecordActionPerformed(evt);
            }
        });

        buttonGroup1.add(deleteServiceRecord);
        deleteServiceRecord.setText("Delete Service Record");
        deleteServiceRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteServiceRecordActionPerformed(evt);
            }
        });

        buttonGroup1.add(viewServiceRecord);
        viewServiceRecord.setText("View Service Records");
        viewServiceRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewServiceRecordActionPerformed(evt);
            }
        });

        submitServiceRecord.setText("Submit");
        submitServiceRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitServiceRecordActionPerformed(evt);
            }
        });

        Home2.setText("Home");
        Home2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Home2ActionPerformed(evt);
            }
        });

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(submitServiceRecord)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewServiceRecord)
                            .addComponent(deleteServiceRecord)
                            .addComponent(updateServiceRecord)
                            .addComponent(addServiceRecord))
                        .addGap(182, 182, 182))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Home2)
                        .addGap(18, 18, 18)
                        .addComponent(Logout)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(addServiceRecord)
                .addGap(18, 18, 18)
                .addComponent(updateServiceRecord)
                .addGap(18, 18, 18)
                .addComponent(deleteServiceRecord)
                .addGap(18, 18, 18)
                .addComponent(viewServiceRecord)
                .addGap(18, 18, 18)
                .addComponent(submitServiceRecord)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Home2)
                    .addComponent(Logout))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitServiceRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitServiceRecordActionPerformed
        // TODO add your handling code here:
        if(addServiceRecord.isSelected()){
            //open add record form
            AddRecord ar = new AddRecord();
            ar.setVisible(true);
            
        } else if(updateServiceRecord.isSelected()){
            //open update record form
            UpdateRecord ur = new UpdateRecord();
            ur.setVisible(true);
            
        } else if(deleteServiceRecord.isSelected()){
            //open delete record form
            DeleteRecord dr = new DeleteRecord();
            dr.setVisible(true);
        } else if(viewServiceRecord.isSelected()){
            //view list of records
            ViewRecord vr = new ViewRecord();
            vr.setVisible(true);
        } else {
            JFrame jf = new JFrame();
            JOptionPane.showMessageDialog(jf,"Please Select an option","ERROR",JOptionPane.ERROR_MESSAGE);
            //throw error
        }
    }//GEN-LAST:event_submitServiceRecordActionPerformed

    private void viewServiceRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewServiceRecordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewServiceRecordActionPerformed

    private void updateServiceRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateServiceRecordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateServiceRecordActionPerformed

    private void deleteServiceRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteServiceRecordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteServiceRecordActionPerformed

    private void Home2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Home2ActionPerformed
        // TODO add your handling code here:
        if((boolean)Intermediate.getItem("isCateringStaff") || (boolean)Intermediate.getItem("isRoomServiceStaff")) {     
            ServiceRecords sr = new ServiceRecords();
            sysExit();
            sr.setVisible(true);
        } else {
            if((boolean)Intermediate.getItem("isFrontDeskStaff")) {     
                FrontDesk fd = new FrontDesk();
                sysExit();
                fd.setVisible(true);
            } else {
                Manager m = new Manager();
                sysExit();
                m.setVisible(true); 
            }
        }  
    }//GEN-LAST:event_Home2ActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        // TODO add your handling code here:
        Login l = new Login();
        sysExit();
        l.setVisible(true);
    }//GEN-LAST:event_LogoutActionPerformed
    public void sysExit(){
        WindowEvent winClosing = new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosing);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServiceRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServiceRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServiceRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServiceRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServiceRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Home;
    private javax.swing.JButton Home1;
    private javax.swing.JButton Home2;
    private javax.swing.JButton Logout;
    private javax.swing.JRadioButton addServiceRecord;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton deleteServiceRecord;
    private javax.swing.JButton submitServiceRecord;
    private javax.swing.JRadioButton updateServiceRecord;
    private javax.swing.JRadioButton viewServiceRecord;
    // End of variables declaration//GEN-END:variables
}
